version: '3'

services:
  mysql:
    image: mysql:8.0.36-debian
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: imersao17
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
