POST http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Category 1",
    "description": "Category 1 description"
}

###

GET http://localhost:8080/category/91db5ff3-34c7-4531-a513-bb00a68ec747 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

POST http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Product 1 description",
    "price": 100,
    "image_url": "http://www.google.com",
    "category_id": "91db5ff3-34c7-4531-a513-bb00a68ec747"
}

###

GET http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/product/ada5823d-23d7-4353-ae89-cf2df41307ab HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/product/category/91db5ff3-34c7-4531-a513-bb00a68ec747 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
